[tox]
envlist = py{39,310,311,312}
skipsdist = True

[testenv]
deps =
    pytest
    pytest-asyncio
    pytest-aiohttp
    aiohttp
    aiohttp-jinja2
    jinja2
commands =
    pytest tests/ -v --tb=short
